/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class ActivitySchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'meta', 'title', 'type'] as const
  $columns = ActivitySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare meta: any | null
  @column()
  declare title: string
  @column()
  declare type: string
}

export class ContributionInfoSchema extends BaseModel {
  static $columns = ['adhesionFeeAmount', 'createdAt', 'id', 'monthlyContributionAmount', 'paymentLimitDay', 'updatedAt'] as const
  $columns = ContributionInfoSchema.$columns
  @column()
  declare adhesionFeeAmount: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare monthlyContributionAmount: number | null
  @column()
  declare paymentLimitDay: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ContributionSchema extends BaseModel {
  static $columns = ['amount', 'contributionMonth', 'createdAt', 'id', 'isComplete', 'memberId', 'note', 'reason', 'rest', 'updatedAt'] as const
  $columns = ContributionSchema.$columns
  @column()
  declare amount: number | null
  @column()
  declare contributionMonth: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isComplete: boolean | null
  @column()
  declare memberId: number | null
  @column()
  declare note: string | null
  @column()
  declare reason: string | null
  @column()
  declare rest: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class MemberSchema extends BaseModel {
  static $columns = ['createdAt', 'firstName', 'id', 'lastName', 'phone', 'updatedAt'] as const
  $columns = MemberSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare firstName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lastName: string | null
  @column()
  declare phone: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ProductSchema extends BaseModel {
  static $columns = ['alertStock', 'available', 'createdAt', 'id', 'name', 'ownerId', 'price', 'quantity', 'updatedAt'] as const
  $columns = ProductSchema.$columns
  @column()
  declare alertStock: number | null
  @column()
  declare available: boolean | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string | null
  @column()
  declare ownerId: number | null
  @column()
  declare price: number | null
  @column()
  declare quantity: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SellSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'owner', 'price', 'productId', 'quantity', 'updatedAt'] as const
  $columns = SellSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare owner: number | null
  @column()
  declare price: number | null
  @column()
  declare productId: number | null
  @column()
  declare quantity: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
